tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
brew "python@3.10"
brew "git"
brew "ansible"
brew "bat"
brew "deno"
brew "geos"
brew "golangci-lint"
brew "htop"
brew "neovim"
brew "numpy", link: false
brew "proj"
brew "python@3.9"
brew "terminal-notifier"
brew "thefuck" 
brew "tmux"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai", args: ["HEAD"]
cask "notunes"
